// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import otto "github.com/robertkrimen/otto"

// Vm is an autogenerated mock type for the Vm type
type Vm struct {
	mock.Mock
}

// Run provides a mock function with given fields: src
func (_m *Vm) Run(src interface{}) (otto.Value, error) {
	ret := _m.Called(src)

	var r0 otto.Value
	if rf, ok := ret.Get(0).(func(interface{}) otto.Value); ok {
		r0 = rf(src)
	} else {
		r0 = ret.Get(0).(otto.Value)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: name, value
func (_m *Vm) Set(name string, value interface{}) error {
	ret := _m.Called(name, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(name, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
